[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
	version = "kubernetes-1.9.9"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"
